= Evaluation

Evaluation is the first step when it comes to building your project. It is performed by your agent as follows:

. At the top-level of your repository, the agent will search for a Nix file to
   evaluate in the following order: `nix/ci.nix`, `ci.nix` or `default.nix`
// TODO: link to how pinning is done
. `NIX_PATH` will be empty. Make sure you pin nixpkgs and not rely on `<nixpkgs>`
    search path. This is to ensure reproducability and purity also when it comes to nixpkgs
. If any of the attributes fail to evaluate, job evaluation phase will be marked as failed
   and error messages will be shown inline per attribute

== Traversal

=== Top level

The top-level value in `nix/ci.nix`, `ci.nix` or `default.nix` may be a https://nixos.org/nix/manual/#ss-functions[function&#8288;icon:external-link[]],
as long as all arguments have default values. Such a function will be invoked and the result must be a https://nixos.org/nix/manual/#ssec-values[value&#8288;icon:external-link[]].

=== Attribute set traversal

The value resulting from <<Top level>> is traversed according to the following rules:

 * If the current value is a derivation, build it asynchronously

 * If the current value is a functor, ignore the attributes, call it and traverse it

 * If the current value is an attribute set and
    ** If it is the root value, traverse *one* level of attributes.
    ** If the attribute set contains `recurseForDerivations = true`, traverse *one* level of attributes.
    ** Otherwise, ignore

 * Otherwise, ignore

Note that for an attribute set `a` it must be the root or it must have `a.recurseForDerivations == true`, which can be added with `pkgs.recurseIntoAttrs`. This must be repeated in every layer of the nested attribute sets. Additionaly, recursion into nested attribute sets is limited to a depth of 10 attributes or functor calls.

=== Example of nested attribute sets

This is an example `ci.nix` that builds `myDrvs.hello`.

```
let
  pkgs = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/${rev}.tar.gz";
  };
in
{
  myDrvs = pkgs.recurseIntoAttrs {
    hello = pkgs.hello;
  };
}
```

== Differences with `nix-build`

The agent expects the root of the file to be an attribute set and traverses it similarly to how `nix build` does it.
A few differences exists:

* Hercules CI allows all attribute names, including ones with characters like `.` that are ignored by `nix build`
* The root must not be a list

