
The goal of this step is to make sure everything is set up correctly. You may

 - If you are familiar with Nix, use your own project to test the agent. It will "nix-build" `nix/ci.nix`, `ci.nix` or `default.nix` with an empty `NIX_PATH`.

 - Alternatively, you may test your setup by following the <<#project-configuration,Project Configuration Guide>>

 - If you only want to verify your setup, use the instructions below.

'''

1. Add this `ci.nix` to a repository in your agent's account.
+
.ci.nix
[source,nix]
----
include::dummy.nix[]
----
+
2. Adapt the attribute set of platforms near the bottom. You can find the agent platforms in the Agents tab in the https://hercules-ci.com/dashboard[dashboard^].
+
3. Browse to the project in the https://hercules-ci.com/dashboard[dashboard^] or click the Details link in the GitHub commit status.
+
If nothing happened, make sure your repository is installed via the "Add GitHub repositories, organizations" button in the https://hercules-ci.com/dashboard[dashboard^] and push a new commit to trigger Hercules CI.
+
Evaluation is https://github.com/hercules-ci/support/issues/24[currently^] only performed on `x86_64-linux` agents. Inspect the agent log if necessary with `journalctl -u hercules-ci-agent`.
+
Build logs are available in the dashboard when done. However some configuration-related errors are reported to `journalctl`, or on macOS: `/var/log/hercules-ci-agent.log`.
+
Contact us at support@hercules-ci.com for any questions or feedback.

'''

This concludes the Setup Guide. To learn more, see

// TODO: Tutorial: Build a Project with Nix
// TODO: Tutorial: Make a Project Multi-Platform

 - The <<#project-configuration,Project Configuration Guide>> 
