WARNING: Although a single agent works with empty `{}` binary cache configuration,
we highly recommend setting up a cache from the start. 
Running without a cache will break some features and will cause unexpectedly long build times
due to eventual garbage collection.

On https://cachix.org[Cachix] you can create a binary cache. After you complete the process, gather the keys into a `binary-caches.json` file, replacing all placeholders:

.binary-caches.json
[source,json]
----
{ "mycache": <1>
    { "kind": "CachixCache"
    , "authToken": "eyJhaf23GH53a.bc23BUSI.9q3048hWHh" <2>
    , "publicKeys": ["mycache.cachix.org-1:EjBSHzF6VmDnzqlldGXbi0RM3HdjfTU3yDRi9Pd0jTY="] <3>
    , "signingKeys": ["uAhqM3jG..."] <4>
    }
}
----
<1> The name of the Cachix cache; for example the `mycache` part from `mycache.cachix.org`.
<2> Omit if you use a local signing key. Required if you use a _Write_ token. You can retrieve one from https://app.cachix.org/[cachix], click a cache, click per cache auth token. Select _Write_ permission and generate a key. If you can only select _Read_ permission, you have to ask a cache admin for a _Write_ token or, if applicable, for the signing key.
<3> The public part of the signing key. Look for "Public Key" on your cache page (example page: `+https://mycache.cachix.org+`).
<4> Omit if you use a _Write_ token. Otherwise, this is the cache-specific secret key to sign store paths. You can find it in `~/.config/cachix/cachix.dhall` or your key backup after following the setup instructions on cachix.org. Make sure you copy the right key if you have multiple in your `cachix.dhall`.

// TODO: xref:hercules-ci-agent:ROOT:binary-cache-json.adoc[The `binary-caches.json` format]
NOTE: For more detail, see https://docs.hercules-ci.com/hercules-ci/reference/binary-caches-json/[The `binary-caches.json` format] in the Reference.
