---
layout: page
title: Setup
---


GitHub
------

Sign in
~~~~~~~

Click the GitHub "Sign in" button on the top right of https://hercules-ci.com[hercules-ci.com].

You will be presented a dialog from GitHub where you can authorize the Hercules CI application to verify your identity.


Install the app
~~~~~~~~~~~~~~~

Now that you are signed in, you are ready to add Hercules CI to your GitHub user account or to a GitHub organization account.

// TODO frontend
Click the "Install hercules-ci application" button near the bottom of https://hercules-ci.com[hercules-ci.com].

GitHub will give you a choice to install the application on all repositories, which includes repositories to be created in the future, or to select specific repositories. We recommend that you make a selection of repositories, in order to prevent that Hercules CI will report commit statuses on repositories that have no suitable Nix expressions, etc.

Collaborators
~~~~~~~~~~~~~

Hercules CI will automatically pick up permissions from GitHub. Collaborators will find the repositories they have access to when they sign in.


Hercules Agent
--------------

Hercules CI lets you deploy your agents on your own infrastructure.

The Hercules agent authenticates itself to the Hercules CI Service by means of tokens.

// TODO frontend
After selecting an account on https://hercules-ci.com[hercules-ci.com], you will find a "Generate agent token" button at the bottom of the page. This produces a private token that should be protected like a password.

[NOTE]
====
The agent token will be used by the agent to request a token that identifies the agent itself. A single agent token can therefore be used to deploy a cluster of agents.
====

[WARNING]
====
When updating the agent token on a previously deployed agent, you may need to remove the `identity.token` file and restart the agent in order to start using the new agent token.
This file is stored in `~/.local/share/hercules-agent` by default.
====

Deploy with NixOps
~~~~~~~~~~~~~~~~~~

// TODO
We will provide a module to simplify the deployment of agents through NixOps.


Run locally
~~~~~~~~~~~

// TODO specifics
You may run the agent on any machine by installing the agent and invoking the `hercules-agent` command. We recommend running the agent on machines that remain connected to the internet.

// TODO is running on your laptop sufficient for some situations?
