= Testing the Agent

1. Add this `ci.nix` to a repository in your agent's account.
+
.ci.nix
[source,nix]
----
include::partial$/snippets/dummy.nix[]
----
+
2. Adapt the attribute set of platforms near the bottom. You can find the agent platforms in the Agents tab in the https://hercules-ci.com/dashboard[dashboard^].
+
3. Browse to the project in the https://hercules-ci.com/dashboard[dashboard^] or click the Details link in the GitHub commit status.
+
If nothing happened, make sure your repository is installed via the "Add GitHub repositories, organizations" button in the https://hercules-ci.com/dashboard[dashboard^] and push a new commit to trigger Hercules CI.
+
Evaluation is https://github.com/hercules-ci/support/issues/24[currently^] only performed on `x86_64-linux` agents. Inspect the agent log if necessary with `journalctl -u hercules-ci-agent`.
+
Build logs are available in the dashboard when done. However some configuration-related errors are reported to `journalctl`, or on macOS: `/var/log/hercules-ci-agent.log`.
+
Contact us at support@hercules-ci.com for any questions or feedback.

'''

This concludes the Setup Guide. To learn more, see

// TODO: Tutorial: Build a Project with Nix
// TODO: Tutorial: Make a Project Multi-Platform

 - The <<#project-configuration,Project Configuration Guide>>
