[[deploy-with-manual-config-file]]
= Deploy manually with a configuration file

If the other deployment methods do not suit your needs, you may choose to run or deploy the agent manually.

[NOTE]
====
Send us an e-mail at support@hercules-ci.com. We can give you advice and
we are interested in expanding our officially supported deployment methods.
====

== 1. Install the agent

[source,shell]
----
$ nix-env -iA hercules-ci-agent -f '<nixpkgs>'
----

== 2. Configure the agent

Write an `agent.toml` file. Most of the entries are optional. A small example:

[source,toml]
----
include::hercules-ci-agent::partial$agent-small-example.toml[]
----

This guide will assume that the xref:hercules-ci-agent:ROOT:agent-config.adoc#baseDirectory[baseDirectory] remains set to `/var/lib/hercules-ci-agent`.

== 3. Get a cluster join token.

include::partial$snippets/GenerateToken.adoc[]

== 4. Configure binary caches

include::partial$snippets/BinaryCachesJson.adoc[]

Install the file in `/var/lib/hercules-ci-agent/secrets/binary-caches.json`.

== 5. Start the agent

Run `hercules-ci-agent --config agent.toml`, preferably via some process supervision system.

== 6. Repository Setup

include::partial$snippets/RepositorySetup.adoc[]
