[[deploy-with-manual-config-file]]
= Deploy manually with a configuration file

If the other deployment methods do not suit your needs, you may choose to run or deploy the agent manually.

[NOTE]
====
Send us an e-mail at support@hercules-ci.com. We can give you advice and
we are interested in expanding our officially supported deployment methods.
====

== 1. Install the agent

include::partial$snippets/CachixBinaries.adoc[]

[source,shell]
----
$ nix-env -iA hercules-ci-agent -f https://github.com/hercules-ci/hercules-ci-agent/tarball/stable
----

== 1. Configure the agent

Write an `agent.toml` file. Most of the entries are optional. A small example:

[source,toml]
----
include::reference:partial$agent-small-example.toml[]
----

This guide will assume that the xref:reference:agent-config.adoc#baseDirectory[baseDirectory] remains set to `/var/lib/hercules-ci-agent`.

== 2. Get a cluster join token.

include::partial$snippets/GenerateToken.adoc[]

== 3. Configure binary caches

include::partial$snippets/BinaryCachesJson.adoc[]

Install the file in `/var/lib/hercules-ci-agent/secrets/binary-caches.json`.

Configure the system to use the caches and accept their public keys.
When using a private cache, you will also need to install an appropriate netrc
file in `/etc/nix/daemon-netrc`.

== 5. Start the agent

Run `hercules-ci-agent --config agent.toml`, preferably via some process supervision system.

== 6. Repository Setup

include::partial$snippets/RepositorySetup.adoc[]
