= Deploy with NixOS

NixOS deployment can be performed on the target machine itself or remotely
by means of `nixos-rebuild --target-host`.

These instructions will use `/etc/nixos` as the location for the configuration
modules. This directory is only used at evaluation time. If you perform remote
deployment, you will use some project directory in place of `/etc/nixos`.

== 1. Bootstrap

include::partial$snippets/CachixBinaries.adoc[]

include::partial$snippets/NixOSBootstrap.adoc[]

== 2. Get a cluster join token.

include::partial$generate-token.adoc[]

== 3. Configure a binary cache

include::partial$snippets/BinaryCachesJson.adoc[]

Continue with an applicable section below.

[discrete]
=== Local deployment

If you're deploying to the local machine, move it to `/var/lib/hercules-ci-agent/secrets/binary-caches.json` and add
this line to your `/etc/nixos/configuration.nix`:

[source,nix]
----
services.hercules-ci-agent.binaryCachesFile = /var/lib/hercules-ci-agent/secrets/binary-caches.json;
----

Make sure that `/var/lib/hercules-ci-agent/secrets` can only be read by `hercules-ci-agent`.

[discrete]
=== Remote deployment

If you're deploying to a remote machine, you need to store it in two locations. One for evaluation,
in the directory of your `configuration.nix` file and one for the deployed agent to read. Add this line to your
 `configuration.nix`:

[source,nix]
----
services.hercules-ci-agent.binaryCachesFile = ./binary-caches.json;
----

Install the same file on the target machine as `/var/lib/hercules-ci-agent/secrets/binary-caches.json`.

Make sure that `/var/lib/hercules-ci-agent/secrets` can only be read `hercules-ci-agent`.

[TIP]
====
*If* your deployment solution lacks a method to store configuration files confidentially,
you may choose to maintain the `binary-caches.json` file separately in both locations.
This allows you to censor the secrets like `{"signingKeys": [], "authToken": ""}` in the file
used for evaluation only.

Make sure not to lose the signing keys and do deploy them to
the target machine!
====

== 4. Activation

Apply the configuration by running `nixos-rebuild switch`.

== 5. Repository Setup

include::partial$snippets/RepositorySetup.adoc[]

== Troubleshooting

To inspect the agent's local log, run `journalctl -u hercules-ci-agent -n 100` on the target machine to see the last 100 lines.
