# based on https://ericjinks.com/blog/2019/netlify-scheduled-build/
name: Trigger Netlify Build
on:
  schedule:
    # Run every 4h
    - cron: '0 */4 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5dc031282c3839a126b9ec22
