= Agent configuration file

When deploying with NixOS, NixOps or nix-darwin you should use the module
documentation instead, or skip ahead to read about less frequently used options
to use with `extraOptions`.

The configuration format for the agent is https://github.com/toml-lang/toml#toml[TOML] markup.
Its location must always be specified by invoking `hercules-ci-agent --config agent.toml`.

A basic `agent.toml` looks as follows:

agent.toml
[source,toml]
----
baseDirectory = "/var/lib/hercules-ci-agent"
concurrentTasks = 4
----

== apiBaseUrl

Optional. Defaults to `https://hercules-ci.com`.

HTTP API agent will connect to.

== baseDirectory

Required.

Directory with all the agent state: secrets, work, etc.

== binaryCachesPath

Optional. Defaults to `_staticSecretsDirectory_/binary-caches.json` if that file exists.

Path to a JSON file containing binary cache secret keys.

Currently only supports http://cachix.org/[Cachix] binary caches.

Note that binary cache configuration affects the whole system's Nix configuration.

Make sure that your system accepts the binary cache. We currently recommend
to look at the
https://github.com/hercules-ci/hercules-ci-agent/search?l=Nix&q=cache[sources]
for details.

Example:

binary-caches.json
[source,json]
----
{ "my-private":
    { "kind": "CachixCache",
      "authToken": "eyJhaf23GH53a.bc23BUSI.9q3048hWHh"
    , "publicKeys": ["my-private.cachix.org-1:EjBSHzF6VmDnzqlldGXbi0RM3HdjfTU3yDRi9Pd0jTY="]
    , "signingKeys": ["XXX"]
    }
}
----

== clusterJoinTokenPath

Optional. Defaults to `_staticSecretsDirectory_/cluster-join-token.key`.

Path to a secret token retrieved when creating a new agent via
https://hercules-ci.com/dashboard.

This token is used for authenticating to `_apiBaseUrl_`.

== concurrentTasks

Optional. Defaults to 4.

Combined number of workers to use for building and evaluating Nix derivations.

The optimal value depends on the resource consumption characteristics of your workload,
including memory usage and in-task parallelism. This is typically determined empirically.

== staticSecretsDirectory

Optional. Defaults to `_baseDirectory_/secrets`.

This is the default directory to look for statically configured secrets like
clusterJoinTokenPath.

== workDirectory

Optional. Defaults to `_baseDirectory_/work`.

The directory in which temporary subdirectories are created for task state.
This includes sources for Nix evaluation.
