:sectlinks:
:sectanchors:
:toc: macro

Hercules CI is a continuous integration service for Nix. In order to provide this service, it connects the following components:

 - hercules-ci.com
 - github.com
// TODO - cachix.org
 - your agent machines

This document describes the steps to set up the integration. The process should be self-explanatory, guided by the https://hercules-ci.com[hercules-ci.com] web application. If you find yourself stuck, or if you want to know the process in advance, this document is intended to provide reference.

[WARNING]
====
This is preview software. We're https://github.com/hercules-ci/support[gathering feedback] to improve the service. It is not meant to be relied upon just yet.

Have a look at our https://github.com/hercules-ci/support/issues?q=is%3Aissue+is%3Aopen+label%3Aroadmap[roadmap] to know what (not) to expect.
====

'''

toc::[]


= Setup Guide

include::setup.adoc[leveloffset=+1]

'''

[[project-setup-and-troubleshooting]]
= Project Configuration and Troubleshooting Guide

include::guide-project-configuration.adoc[leveloffset=+1]

'''

= FAQ / How To

== My commit status is stuck in Pending - Waiting for agent

Make sure you've deployed an agent. If the agent didn't start, it should leave a message in the system journal. To see the last 100 lines of the journal with NixOps, run `nixops ssh agent journalctl -u hercules-ci-agent -n 100`

Note that an agent can currently only be assigned to a single account. Assigning agents to multiple accounts is on the roadmap, but for now you will have to run multiple agents to build for multiple accounts.

== Can I disable an attribute? I don't want to build it on CI.

You can exclude attributes by putting them inside an attribute set without `recurseIntoAttrs`. This way, you can still use the attribute for other purposes, but it will not show up in CI. For example:

[source,nix]
----
# default.nix
let pkgs = import ./nix {};
in {
  inherit (pkgs) myProject;
  shells = {
    projectShell = pkgs.mkShell {
      buildInputs = [ pkgs.nixops ];
    };
  };
}
----

[source,nix]
----
# shell.nix
(import ./default.nix).shells.projectShell
----

[source,bash]
----
$ nix-build
/nix/store/...-hello-2.10
$ nix-shell --run 'nixops --version'
NixOps 1.6.1
----
== My attribute doesn't show up in the evaluation

Is it in a nested attribute set? Make sure you call `pkgs.recurseIntoAttrs` on all levels of nested attrsets.

Does `nix-build` build the attribute with specifying `-A`? If it doesn't, Hercules CI shouldn't build it either. Otherwise, please contact us.

== How can I manually trigger a build?

You can trigger a rebuild of a derivation in the web interface. Evaluations can be triggered by pushing a branch. You may use a temporary branch just to trigger an evaluation and commit status update.

== Where is the evaluation log?

A log of the evaluation is not available yet. Normally this should not be needed, however, we do want to show the `builtins.trace` messages in the future.

To troubleshoot unexpected technical failures of evaluation on the agent, you may inspect the agent log.

== My derivation is taking long and there's no build log yet. What's going on?

Derivation logs are currently only available after the derivation has succeeded or failed.

You may run `nix-store --realise /nix/store/<...>.drv` on an agent for troubleshooting purposes.

== What are the `nix-store --realise` processes about?

The agent talks to Nix via `nix-store` to build derivations.
Each of these processes is for building a single derivation, which may include
fetching the closure of dependencies.

== Some build logs appear in the agent log (journalctl etc) but not all of them?

Only evaluation currently logs to the agent log. Evaluation may include some
building if you use import from derivation.

'''

= Reference

== Evaluation

include::autogenerate/Evaluation.adoc[leveloffset=+1]

include::reference-binary-caches-json.adoc[leveloffset=+1]

include::agent-config.adoc[leveloffset=+1]
